### ISSUE TITLE
Latest Visual C++ 2022 version in Windows images has a SIMD optimization bug that makes it unreliable

### ISSUE THREAD

**Issue by lballabio** [actions/runner-images#12470]
### Description

See <https://developercommunity.visualstudio.com/t/Code-optimization-bug-SIMD-std::transf/10912292>.  A fix is pending release, but in the meantime it would help to downgrade to a working version.

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [x] Windows Server 2022
- [ ] Windows Server 2025

### Image version and build link

The problem started in windows-2022 version: 20250617.1.0, e.g. <https://github.com/lballabio/QuantLib/actions/runs/15800989037/job/44539149267>.

### Is it regression?

The build worked in windows-2022 version 20250609.2.0, e.g. <https://github.com/lballabio/QuantLib/actions/runs/15657466165>

### Expected behavior

The test suite should run without reporting any errors.

### Actual behavior

The generated code is incorrect leading to test suite failures.

### Repro steps

A simple C++ file and compilation command line is available at <https://developercommunity.visualstudio.com/t/Code-optimization-bug-SIMD-std::transf/10912292>.

**Comment by lballabio** [comment]
The working image had the MSVC toolset 14.43.34808 installed; the non-working image has 14.44.35207.

**Comment by vidyasagarnimmagaddi** [comment]
HI @lballabio , Thank you for bringing this issue to our attention. We will look into this issue and will update you after investigating.

**Comment by cacti77** [comment]
Many of my Windows DevOps jobs have started failing since the upgrade from the 20250609.2.0 version of the 'windows-latest' image to the 20250617.1.0 one; see [here](https://learn.microsoft.com/en-us/answers/questions/2286683/multiple-devops-pipeline-job-failures-since-roll-o). This may be related to what you're seeing too.

**Comment by cacti77** [comment]
> in the meantime it would help to downgrade to a working version.

100% agree! We've currently reverted to 'windows-2019' as a temporary workaround ('windows-2025' seems to have the same issues as 'windows-2022') but that will apparently [be withdrawn](https://github.com/actions/runner-images/issues/12045) on 30 June!

**Comment by flomnes** [comment]
One of our CI jobs is failing, possibly because of this. Is there any workaround ? We tried disabling optimizations through `/Od`, but it didn't work.

**Comment by alexbal7** [comment]
> One of our CI jobs is failing, possibly because of this. Is there any workaround ? We tried disabling optimizations through `/Od`, but it didn't work.

You can wait for the fix 

![Image](https://github.com/user-attachments/assets/58286576-7e98-4d17-bba2-16e06b39514f)

**Comment by alexbal7** [comment]
> One of our CI jobs is failing, possibly because of this. Is there any workaround ? We tried disabling optimizations through `/Od`, but it didn't work.

You can wait for the fix who is pending release.

**Comment by AniLeo** [comment]
I also tried /Od and it didn't work

We are also impacted at RPCS3 with https://github.com/RPCS3/rpcs3/issues/17326

There should really be a runner image running on the previous msbuild version so we could switch to that while the issue gets addressed. We can't even go back to windows-2022 since the msbuild version is the same as windows-2025.

**Comment by kishorekumar-anchala** [comment]
HI @lballabio @cacti77 , If i am not mistaken , this might fix with the newer version of visual studio and we'll confirm once the newer version deployed .

**Comment by AniLeo** [comment]
@kishorekumar-anchala is it not possible to have a rollback to the last working version on the CI image until the new version with the fix is available?

**Comment by AniLeo** [comment]
@alexbal29 that has nothing to do with the issue at hand

**Comment by antoniodesousa** [comment]
> HI @lballabio @cacti77 , If i am not mistaken , this might fix with the newer version of visual studio and we'll confirm once the newer version deployed .

@kishorekumar-anchala is there an ETA of when it's going to be deployed? It has been 2 weeks since your post...

**Comment by kishorekumar-anchala** [comment]
Hi @antoniodesousa @lballabio - Kindly verify now with latest image rollout and confirm back . Thank you !

**Comment by antoniodesousa** [comment]
@kishorekumar-anchala if you are referring to 17.14.8, it did not fix the regression on this project https://github.com/RPCS3/rpcs3/issues/17326

**Comment by kishorekumar-anchala** [comment]
> [@kishorekumar-anchala](https://github.com/kishorekumar-anchala) if you are referring to 17.14.8, it did not fix the regression on this project [RPCS3/rpcs3#17326](https://github.com/RPCS3/rpcs3/issues/17326)

Could you please elaborate your issue and share me the re production steps to investigate ?

**Comment by lballabio** [comment]
> Hi @antoniodesousa @lballabio - Kindly verify now with latest image rollout and confirm back . Thank you !

@kishorekumar-anchala The latest image rollout still contains the same compiler version as the previous one, see e.g. the build at https://github.com/lballabio/QuantLib/actions/runs/16242184240/job/45860099511

From the logs:

in the "Set up job" step:

> Runner Image
>  Image: windows-2022
>  Version: 20250710.1.0
>  Included Software: https://github.com/actions/runner-images/blob/win22/20250710.1/images/windows/Windows2022-Readme.md
>  Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20250710.1

in the "Build" step:

> ClCompile:
>  C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.44.35207\bin\HostX64\x64\CL.exe 

14.44.35207 is the same compiler version used in the jobs failing three weeks ago, e.g., https://github.com/lballabio/QuantLib/actions/runs/15800989037/job/44539149267

**Comment by kishorekumar-anchala** [comment]
Thank you for the confirmation. We were expecting the new version to be available last week, but unfortunately, it was delayed. We will notify you once the fix is released by the upstream team.

cc @lballabio @AniLeo @antoniodesousa @cacti77

**Comment by lballabio** [comment]
@kishorekumar-anchala  A new version of Visual C++ was in fact released on July 8th, see https://learn.microsoft.com/en-gb/visualstudio/releases/2022/release-notes?tabs=allfeatures

As I said above it was not included in your latest rollout, though, so I can't say if that version fixes the problem.  If it doesn't, we're looking at least at another month of unusable images.  Have you considered pinning the compiler to an earlier version?

**Comment by kishorekumar-anchala** [comment]
> [@kishorekumar-anchala](https://github.com/kishorekumar-anchala) A new version of Visual C++ was in fact released on July 8th, see https://learn.microsoft.com/en-gb/visualstudio/releases/2022/release-notes?tabs=allfeatures
> 
> As I said above it was not included in your latest rollout, though, so I can't say if that version fixes the problem. If it doesn't, we're looking at least at another month of unusable images. Have you considered pinning the compiler to an earlier version?

No, I haven't pinned the compiler to an earlier version. However, if your workflow allows it, you might consider doing so temporarily until the issue is resolved in a future rollout.

**Comment by lballabio** [comment]
Well, I can't use a different version of the compiler if it's not installed in the runner image, can I? 😄

**Comment by kishorekumar-anchala** [comment]
You're right—switching compiler versions isn't possible unless the runner image includes support for it. In the meantime, we may need to consider escalating the issue upstream. Hopefully, the upcoming rollout will address the problem.

**Comment by alexbal29** [comment]
@kishorekumar-anchala Fixed on 17.14.9 

<img width="1290" height="2796" alt="Image" src="https://github.com/user-attachments/assets/373e3d08-9a0a-4172-bf0a-89b667317369" />

**Comment by alexbal29** [comment]
> Thank you for the confirmation. We were expecting the new version to be available last week, but unfortunately, it was delayed. We will notify you once the fix is released by the upstream team.

The issue is only fixed on 17.14.9 

<img width="1290" height="2796" alt="Image" src="https://github.com/user-attachments/assets/b58adabc-b05d-40c3-9fd8-1c10e17df4c3" />

**Comment by alexbal29** [comment]
> You're right—switching compiler versions isn't possible unless the runner image includes support for it. In the meantime, we may need to consider escalating the issue upstream. Hopefully, the upcoming rollout will address the problem.

The bug is fixed only on 17.14.9 

<img width="1290" height="2796" alt="Image" src="https://github.com/user-attachments/assets/df98bd32-36dc-4426-893e-071860dc3f56" />

**Comment by alexbal29** [comment]
> You're right—switching compiler versions isn't possible unless the runner image includes support for it. In the meantime, we may need to consider escalating the issue upstream. Hopefully, the upcoming rollout will address the problem.

The Windows 2022 and Windows 2025 image iodate on pull request does not have 17.14.9 who fix the bug 

<img width="1290" height="2796" alt="Image" src="https://github.com/user-attachments/assets/f7be6883-04af-40f9-89be-8e3706d552c7" />

**Comment by alexbal29** [comment]
@kishorekumar-anchala The bug is fixed on VS 17.14.9 

<img width="1290" height="2796" alt="Image" src="https://github.com/user-attachments/assets/939cb172-4335-4ee2-9b00-bd3c84679407" />

**Comment by alexbal29** [comment]
Confirmed fixed on microsoft solution  

<img width="1290" height="2796" alt="Image" src="https://github.com/user-attachments/assets/e7adac89-e4fe-46bd-b6ae-b997d5522b6e" />

**Comment by kishorekumar-anchala** [comment]
This version will be available with the next week image rollout and will update the same . thansk you for the support !

**Comment by vidyasagarnimmagaddi** [comment]
HI all, the latest image has been rolled out with `20250720.1` , kindly check at your end .thanks

**Comment by lballabio** [comment]
The latest rollout worked for me, thanks.

**Comment by kishorekumar-anchala** [comment]
@lballabio - thanks for the confirmation , closing the issue as completed.
