### ISSUE TITLE
Windows-11-arm GUI system tests can fail due to privacy settings taking focus

### ISSUE THREAD

**Issue by LeonarddeR** [actions/runner-images#14069]
**Type of issue**
- Other

**Describe the issue**
Windows 11 has a first run experience to set privacy settings. This first experience isn't suppressed in the windows-11-arm image.

**To Reproduce**
Run any system test that relies on automated GUI testing, as used in [NVDA](https://github.com/nvaccess/nvda) system tests.

**Expected behavior**
No privacy settings window sitting in the way.

**Screenshots**
<img width="1024" height="768" alt="Screenshot" src="https://github.com/user-attachments/assets/201efdbe-3013-4b7f-a599-3674c8880bdd" />

**Desktop (please complete the following information):**
 - OS: Windows 11 ARM64

**Comment by jeremyd2019** [comment]
Even though these `OOBE` settings are deprecated iirc, they still seem to work for me in my Unattend.xml when I set up my own self-hosted runner image

```xml
<?xml version="1.0" encoding="utf-8"?>
<unattend xmlns="urn:schemas-microsoft-com:unattend">
    <settings pass="oobeSystem">
        <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <OOBE>
                <HideEULAPage>true</HideEULAPage>
                <HideLocalAccountScreen>true</HideLocalAccountScreen>
                <HideOEMRegistrationScreen>true</HideOEMRegistrationScreen>
                <HideOnlineAccountScreens>true</HideOnlineAccountScreens>
                <HideWirelessSetupInOOBE>true</HideWirelessSetupInOOBE>
                <NetworkLocation>Other</NetworkLocation>
                <ProtectYourPC>3</ProtectYourPC>
                <SkipMachineOOBE>true</SkipMachineOOBE>
                <SkipUserOOBE>true</SkipUserOOBE>
            </OOBE>
        </component>
    </settings>
</unattend>
```

**Comment by LeonarddeR** [comment]
I tried to kill `WWAHost.exe` before running the tests, but that doesn't seem to be enough. I'm getting a full screen start menu in that case.

**Comment by Kichura** [comment]
> Even though these `OOBE` settings are deprecated iirc, they still seem to work for me in my Unattend.xml when I set up my own self-hosted runner image
> 
> <?xml version="1.0" encoding="utf-8"?>
> <unattend xmlns="urn:schemas-microsoft-com:unattend">
>     <settings pass="oobeSystem">
>         <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
>             <OOBE>
>                 <HideEULAPage>true</HideEULAPage>
>                 <HideLocalAccountScreen>true</HideLocalAccountScreen>
>                 <HideOEMRegistrationScreen>true</HideOEMRegistrationScreen>
>                 <HideOnlineAccountScreens>true</HideOnlineAccountScreens>
>                 <HideWirelessSetupInOOBE>true</HideWirelessSetupInOOBE>
>                 <NetworkLocation>Other</NetworkLocation>
>                 <ProtectYourPC>3</ProtectYourPC>
>                 <SkipMachineOOBE>true</SkipMachineOOBE>
>                 <SkipUserOOBE>true</SkipUserOOBE>
>             </OOBE>
>         </component>
>     </settings>
> </unattend>

This is nearly correct but you can skip all of that in favor of `ProtectYourPC` being set to **3** while at the same time including `DisablePrivacyExperience` in `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\OOBE` which is set to **1** to skip the privacy-related OOBE on first login for all users.

**Comment by jay0lee** [comment]
For the hosted Windows ARM64, I was able to work around this by using Appium to dismiss the dialog and get to the regular desktop. Here's the relevant Appium code that I run only on Win arm64:

https://github.com/GAM-team/actions-hello-world/blob/master/ssd.mjs#L41-L58

I'd definitely like to see this fixed in the next image release. Thanks for working on this!

**Comment by LeonarddeR** [comment]
@pbk8s May I ask whether this is on the radar for the next release of the image?

**Comment by pbk8s** [comment]
@LeonarddeR Yes, working on getting it in the next iteration.

**Comment by LeonarddeR** [comment]
Unfortunately, the new ARM image still doesn't give a working desktop. Looks like there's stil a OneDrive OBE popup sitting in the way:

<img width="1024" height="768" alt="Screenshot" src="https://github.com/user-attachments/assets/8a78d304-7c7c-415b-b856-6bafda76dbde" />

**Comment by LeonarddeR** [comment]
The same image also auto-runs `wsl.exe --update --confirm --prompt-before-exit` around logon, which opens a Windows Terminal window that likewise takes foreground (with a 60-second prompt) and breaks the same GUI tests.

<img width="1024" height="768" alt="Image" src="https://github.com/user-attachments/assets/2ce28742-6dd2-466e-be62-45ef605f8502" />

**Comment by EDM115** [comment]
it's been a year and I can't believe this is still an issue ffs

**Comment by LeonarddeR** [comment]
I must admit that I somehow share that surprise to some extend. It is slightly strange to see new versions come and new versions go without addressing any longstanding bugs.

**Comment by EDM115** [comment]
btw thank you so much Leonard for the linked commits, really helped me troubleshoot this and make my automated tests working 🫶

**Comment by Caitlyn50** [comment]
> it's been a year and I can't believe this is still an issue ffs

They said they work to fix it in June 

<img width="660" height="1434" alt="Image" src="https://github.com/user-attachments/assets/bad6a08f-a4c0-45d8-9b95-779192cff4c0" />

**Comment by EDM115** [comment]
> They said they work to fix it in June

well I opened a PR to fix it, let's see if it'll get merged soon or if we need to keep using workarounds for months on end

**Comment by Caitlyn50** [comment]
> it's been a year and I can't believe this is still an issue ffs

I have open a issue to ask about a update on this issue.

**Comment by Tristana14** [comment]
> it's been a year and I can't believe this is still an issue ffs

It why i have reported it again on issues.

**Comment by v-dunjadenic** [comment]
Hi, sorry for the delay on this. I'll pick this up and investigate the issue, review the proposed fixes, and see what our options are. Thanks for all the contributions so far.

**Comment by ghost** [comment]
> Hi, sorry for the delay on this. I'll pick this up and investigate the issue, review the proposed fixes, and see what our options are. Thanks for all the contributions so far.

@v-dunjadenic Can also pick this up https://github.com/actions/runner-images/issues/14264 ?

**Comment by ghost** [comment]
> I must admit that I somehow share that surprise to some extend. It is slightly strange to see new versions come and new versions go without addressing any longstanding bugs.

They work to fix it.
