### ISSUE TITLE
Update Xcode 14

### ISSUE THREAD

**Issue by knox** [actions/runner-images#6199]
### Tool name

Xcode 14

### Tool license

Apple

### Add or update?

- [ ] Add
- [X] Update

### Desired version

14 Release Candidate

### Brief description of tool

An update to the latest version is desired to build and publish for the new iOS 16 which will be released to the public on sep 12th

```
Apps for the following platforms built using Xcode 14 Release Candidate can now be submitted to the App Store:

* iOS 16 and iPadOS 16
* tvOS 16
* watchOS 9
```

https://developer.apple.com/news/releases/?id=09072022h

### URL for tool's homepage

https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Virtual environments where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by enricenrich** [comment]
I agree with @knox. 

@al-cheb The release of iOS 16, iPadOS 16, watchOS 9, and tvOS 16 will happen on Monday, September 12th. To ensure that our updates are ready for that date, we must submit the builds with the Xcode 14 RC build before tomorrow. We can't wait until next week.

**Comment by miketimofeev** [comment]
Considering the importance of this update we will start the rollout today and finish it by tomorrow.

**Comment by dungi** [comment]
Thank you @miketimofeev

**Comment by miketimofeev** [comment]
We have deployed the new image with the Xcode 14 RC on board, however, it turned out that to continue developing apps for macOS Ventura Xcode 14 beta is required (see comment https://github.com/actions/runner-images/pull/6201#discussion_r966051218) so we will deploy the new image with both Xcodes early next week.

**Comment by bdrelling** [comment]
@miketimofeev I'm seeing an extremely weird issue that I'm not sure how to explain.

On `macos-12` with Xcode 14.0, when I run `xcodebuild -showdestinations` on GitHub Actions, I see the following devices for watchOS simulator:

```sh
{ platform:watchOS Simulator, id:405B2268-4DEF-4F41-95BF-0D80A85E9BE2, OS:9.0, name:Apple Watch SE (44mm) (2nd generation) }
{ platform:watchOS Simulator, id:A3AFFD33-D827-437E-901F-F1BBCBB5B8B5, OS:9.0, name:Apple Watch Series 5 (40mm) }
{ platform:watchOS Simulator, id:DA6F1C23-2247-446E-8F93-0F9C145FC21A, OS:9.0, name:Apple Watch Series 5 (44mm) }
{ platform:watchOS Simulator, id:72334C06-F42F-434C-9DBC-E78B80253F2E, OS:9.0, name:Apple Watch Series 6 (40mm) }
{ platform:watchOS Simulator, id:9262F74D-B690-41AB-B75F-0B47B97657E9, OS:9.0, name:Apple Watch Series 6 (44mm) }
{ platform:watchOS Simulator, id:3B6CE32D-7B41-416F-8763-0A4359A157C0, OS:9.0, name:Apple Watch Series 7 (41mm) }
{ platform:watchOS Simulator, id:FC78DD10-9B45-426B-B3F3-778F06B6C2A8, OS:9.0, name:Apple Watch Series 7 (45mm) }
{ platform:watchOS Simulator, id:7CA7CDD9-2B6C-453A-BF15-0BEB35582C9B, OS:9.0, name:Apple Watch Series 8 (41mm) }
{ platform:watchOS Simulator, id:634C9C2B-E204-4306-94B3-C13C0E1332C6, OS:9.0, name:Apple Watch Series 8 (45mm) }
{ platform:watchOS Simulator, id:4CCC17DF-346B-4DBF-A832-A6199F8256DA, OS:9.0, name:Apple Watch Ultra (49mm) }
```
but locally, I see the following:
```sh
{ platform:watchOS Simulator, id:76273A6B-6225-4C91-9240-E1B376B3B56E, OS:9.0, name:Apple Watch SE (44mm) (2nd generation) }
{ platform:watchOS Simulator, id:4DD12E9E-4BA9-498E-B835-5000A1D5C796, OS:9.0, name:Apple Watch Series 5 - 40mm }
{ platform:watchOS Simulator, id:593D7867-2607-4A34-BACC-327389E6BADE, OS:9.0, name:Apple Watch Series 5 - 44mm }
{ platform:watchOS Simulator, id:3CAB580A-C1F6-4F2D-B4A5-C3CE56A21443, OS:9.0, name:Apple Watch Series 6 - 40mm }
{ platform:watchOS Simulator, id:A90AD6C0-CE9E-40D0-948C-3EDF279B71CB, OS:9.0, name:Apple Watch Series 6 - 44mm }
{ platform:watchOS Simulator, id:4640E104-D62E-46D7-BEAA-1705A3C31CBB, OS:9.0, name:Apple Watch Series 7 - 41mm }
{ platform:watchOS Simulator, id:B5918C6C-C20A-4198-8826-8130407C03AC, OS:9.0, name:Apple Watch Series 7 - 45mm }
{ platform:watchOS Simulator, id:116403AF-8328-41D6-9B6E-26F097E05110, OS:9.0, name:Apple Watch Series 8 (41mm) }
{ platform:watchOS Simulator, id:83839886-E966-43D8-AEB9-D48C1108EE2B, OS:9.0, name:Apple Watch Series 8 (45mm) }
{ platform:watchOS Simulator, id:C6E5229E-69E5-46C5-9E18-7D0AB59361EE, OS:9.0, name:Apple Watch Ultra (49mm) }
```

For running tests via `xcodebuild test`, an exact simulator name has to be specified, but the two don't match.

I can verify that the `macos-12` runner has the correct version of Xcode 14.0:

```sh
> Run maxim-lobanov/setup-xcode@v1
Switching Xcode to version '14.0'...
Xcode is set to 14.0.0 (14A309)
```

And it matches my local version:

```sh
$ xcodebuild -version
Xcode 14.0
Build version 14A309
```

The only thing I can think of that would be different is that the method for installing simulators might be automated somehow differently for the runners, but I used the UI.

I really hope this made sense -- this is a really weird one...

**Comment by miketimofeev** [comment]
@bdrelling hi! Yeah, we install watchos and tvos simulators additionally using `xcodebuild -downloadAllPlatforms` command (see https://github.com/actions/runner-images/issues/6051). Could you check locally if there is the same behavior when using a command rather than GUI?

**Comment by knox** [comment]
> We have deployed the new image with the Xcode 14 RC on board

You are refering to #6201 i guess. For me this issue is resolved and i'd close it, not?

**Comment by miketimofeev** [comment]
@knox feel free to close it, thank you.

**Comment by knox** [comment]
@miketimofeev maybe you update these tags for clarification. Thank you very much for resolving this so instantly.

**Comment by bdrelling** [comment]
@miketimofeev I won't have access to a clean machine to run that command on for a few days, so I won't be able to test that, but to be clear: if running that command does fix it locally, that still won't fix it for the majority of local Xcode installations where users are not running that command, meaning a local vs. CI mismatch, so GitHub Actions should still be the one to rename those incorrectly named simulators, right? And additionally file a bug with Apple if the names don't match.

Also, let me know if you want me to open as a new issue now that this is closed, or anywhere else. Thanks!

**Comment by miketimofeev** [comment]
@bdrelling yes, please, open a new issue as it's not clear for now how to rename them so we need to investigate the issue further.

**Comment by Brett-Best** [comment]
> ```shell
> { ... name:Apple Watch SE (44mm) (2nd generation) }
> { ... name:Apple Watch Series 5 (40mm) }
> { ... name:Apple Watch Series 5 (44mm) }
> { ... name:Apple Watch Series 6 (40mm) }
> { ... name:Apple Watch Series 6 (44mm) }
> { ... name:Apple Watch Series 7 (41mm) }
> { ... name:Apple Watch Series 7 (45mm) }
> { ... name:Apple Watch Series 8 (41mm) }
> { ... name:Apple Watch Series 8 (45mm) }
> { ... name:Apple Watch Ultra (49mm) }
> ```

I’m seeing this locally on my iMac btw.

**Comment by miketimofeev** [comment]
@Brett-Best do you install simulators the same way via command-line?

**Comment by Brett-Best** [comment]
No, installed the simulators using the Xcode dialog that comes up when you launch Xcode for the first time @miketimofeev - that sounded like the way @bdrelling was doing it too (?)

**Comment by bdrelling** [comment]
@Brett-Best thank you for confirming via the Xcode dialog. I’ve installed locally twice on two machines and saw the same result. One machine had Xcode previously, the other did not.

I’ll open a new issue, but wouldn’t mind if others could confirm as well! If it’s somehow just my install, it’ll help to narrow it down so I can submit a Radar. Thanks!

**Comment by bdrelling** [comment]
Well, I previously thought the biggest issue would be that my scripts wouldn't work when running Xcode for UI-installed simulators versus CLI-installed simulators. However, even within GitHub Actions' `macos-12` runner, the simulators are inconsistent from Xcode 12 and 13 as well, so it's not just an issue of local/remote, but an issue of naming across multiple installations of Xcode.

Opened up a new issue here: https://github.com/actions/runner-images/issues/6243

Thanks all!

**Comment by al-cheb** [comment]
> any news on Xcode 14.1 image being available ?

@stancho-stanchev , xcode 14.1 is available on macOS-12 - [Python One-Liners](https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md#xcode)

**Comment by Brett-Best** [comment]
What OS have you specified in the workflow?

**Comment by kopax-polyconseil** [comment]
We still encounter issue having hermes with this version: see  https://github.com/facebook/react-native/issues/35536 , any clue ?
