### ISSUE TITLE
azure.archive.ubuntu.com is unstable again

### ISSUE THREAD

**Issue by RadxaYuntian** [actions/runner-images#7048]
### Description

Similar to recent reported issue #6894 #6909 #6913, runner is not able to connect to azure.archive.ubuntu.com to fetch all packages.
`apt update` appears unaffected.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

ubuntu-22.04: https://github.com/radxa-build/rock-4se/actions/runs/4102124998

### Is it regression?

No

### Expected behavior

`apt install` completes successfully.

### Actual behavior

`apt install` could not complete due to network related issue.

### Repro steps

Rerun failed job.

**Comment by jlaine** [comment]
I can confirm I'm experiencing the same issue.

**Comment by provokateurin** [comment]
Same here

**Comment by ddobranic** [comment]
Hello, it is something out of our control. As you can [see](https://github.com/actions/runner-images/issues/675#issuecomment-1382027536) previous time it was an issue with Canonical servers.

**Comment by EmilioCarasa** [comment]
Im experiencing this same issue with Ubuntu 18.04

**Comment by KristapsT** [comment]
Experiencing the same on Ubuntu 22.04 on Large Runners.

**Comment by szmmar** [comment]
Same here

**Comment by jlaine** [comment]
Hi @ddobranic ,

> Hello, it is something out of our control. As you can [see](https://github.com/actions/runner-images/issues/675#issuecomment-1382027536) previous time it was an issue with Canonical servers.

Given how frequent this issue is, doesn't it highlight the limits of the "caching proxy" approach? Wouldn't it be more reliable to set up an actual *mirror* so that upstream downtime only affects syncing the mirror, not CI runs?

**Comment by akbast** [comment]
Same here

**Comment by bdo** [comment]
This affects us pretty badly here at Warner Bros. Discovery!

**Comment by florian-hoenicke** [comment]
We also have issues. What is a workaround we could do?

**Comment by karmab** [comment]
someone mentioned `sed -i 's/azure\.//' /etc/apt/sources.list` before `apt-get update`
worth a shot if you cant wait for azure network issues to be fixed

**Comment by nstng** [comment]
Same issue here using the ubuntu sources, e.g.,
```
Could not connect to archive.ubuntu.com:80 (185.125.190.39), connection timed out Could not connect to archive.ubuntu.com:80
```

**Comment by mikhailkoliada** [comment]
Hello! 
It has been handed over to the appropriate team! 
We will post the updates.

**Comment by bdo** [comment]
> sed -i 's/azure\.//' /etc/apt/sources.list

Thanks @karmab, but this didn't work for me.

**Comment by RooGhz720** [comment]
same here can't fetch package

**Comment by LiliDeng** [comment]
We have created ubuntu support case, they will response within 15 mins.

**Comment by AlexanderLanin** [comment]
FYI setting apt to retry 10 times as suggested somewhere else **does not help**. It just takes longer to fail on a random package.

`echo 'Acquire::Retries "10";' | sudo tee -a /etc/apt/apt.conf.d/80-retries > /dev/null`

**Comment by LiliDeng** [comment]
canonical's reply 
`This appears to be a downstream issue related to a current Ubuntu infra incident. Working on getting more information on root cause and ETTR. I'll update you shortly.`

**Comment by aqeelat** [comment]
@LiliDeng could you please tell them to update https://status.canonical.com/

**Comment by aqeelat** [comment]
@mikhailkoliada Would we still get billed for the failing actions? I have multiple runs that took about 45 minutes on the apt step alone.

**Comment by LiliDeng** [comment]
> @LiliDeng could you please tell them to update https://status.canonical.com/

I have asked this in the canonical case.

**Comment by florian-hoenicke** [comment]
@RadxaYuntian the 20.04 runner is also impacted

**Comment by mefistotelis** [comment]
When I click the failing link, I can download the deb no problem. Is the issue specific to connection between github and canonical?

**Comment by LiliDeng** [comment]
> When I click the failing link, I can download the deb no problem. Is the issue specific to connection between github and canonical?

no, it is not related with github, when we try to install the package or apt update on azure vm, it also has this issue.

**Comment by aqeelat** [comment]
It worked for a minute but it is broken again.

**Comment by florian-hoenicke** [comment]
Can you quickly post a workaround we can do until it is fixed?
Something like the modification of the /etc/apt/sources.list to use another mirror?

**Comment by rafrafek** [comment]
Add this step before your `apt-get install` step. It's slow but it works:
```yaml
      - name: Update apt - with apt-spy2 workaround
         run: |
           sudo gem install apt-spy2
           sudo apt-spy2 check
           sudo apt-spy2 fix --commit
           sudo apt-get update
```

**Comment by aloisklink** [comment]
>  Can you quickly post a workaround we can do until it is fixed?
> Something like the modification of the /etc/apt/sources.list to use another mirror?

The following works pretty well for me:

```yaml
    - name: Set apt mirror
      # GitHub Actions apt proxy is super unstable
      # see https://github.com/actions/runner-images/issues/7048
      run: |
        # make sure there is a `\t` between URL and `priority:*` attributes
        printf 'http://azure.archive.ubuntu.com/ubuntu	priority:1\n' | sudo tee /etc/apt/mirrors.txt
        curl http://mirrors.ubuntu.com/mirrors.txt | sudo tee --append /etc/apt/mirrors.txt
        sudo sed -i 's/http:\/\/azure.archive.ubuntu.com\/ubuntu\//mirror+file:\/etc\/apt\/mirrors.txt/' /etc/apt/sources.list
```

It downloads the official `mirrors.txt` file from http://mirrors.ubuntu.com/mirrors.txt but we append `http://azure.archive.ubuntu.com/ubuntu	priority:1\n` (note that there is a tab, not a space between the URL and `priority:1` so that apt always tries the faster `http://azure.archive.ubuntu.com/ubuntu` mirror first, and only falls back to the other entries in `mirrors.txt` on failure.

See [*apt-transport-mirror(1)* man-page](https://manpages.ubuntu.com/manpages/jammy/en/man5/sources.list.5.html) for more details on how `apt` mirrors works.

**Comment by RadxaYuntian** [comment]
Issue appears to be resolved: https://github.com/radxa-build/rock-4se/actions/runs/4109805293

**Comment by brunobertechini** [comment]
This keeps coming back every once in a while :(

**Comment by sebthom** [comment]
@brunobertechini you can give this a try https://github.com/vegardit/fast-apt-mirror.sh

**Comment by therealdwright** [comment]
This is impacting us also - it's quite frustrating.

**Comment by LiliDeng** [comment]
> This is impacting us also - it's quite frustrating.

Ubuntu case created https://canonical.force.com/ua/s/case/5008e00000CiHzTAAV/could-not-connect-to-azurearchiveubuntucom80-52147219192-connection-timed-out-ip-52147219192-80

do you see the repo server ip, is it also `52.147.219.192`?

**Comment by Flexba** [comment]
Also impacting me - the IPs encountered are
* `51.107.8.243`
* `51.116.128.6`

**Comment by LiliDeng** [comment]
> 

let me update them into case, thank you!

**Comment by LiliDeng** [comment]
> Also impacting me - the IPs encountered are
> 
> * `51.107.8.243`
> * `51.116.128.6`
I have updated them into above case, thank you!

**Comment by LiliDeng** [comment]
@Flexba @therealdwright hi, has the issue resolved in your side?

**Comment by Flexba** [comment]
Yes, resolved for me

**Comment by jaboutboul** [comment]
I can confirm this is now resolved on Canonical’s end

**Comment by qaiserali** [comment]
This is also impacting us. Any fix for it?

**Comment by LiliDeng** [comment]
> This is also impacting us. Any fix for it?

is still on-going? please copy the error message

**Comment by qaiserali** [comment]
> > This is also impacting us. Any fix for it?
> 
> is still on-going? please copy the error message

We are getting the following error
`Unable to connect to azure.archive.ubuntu.com:http:
Err:19 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 xxd amd64 2:8.1.2269-1ubuntu5.13
  Unable to connect to azure.archive.ubuntu.com:http:
Err:20 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 vim-common all 2:8.1.2269-1ubuntu5.13
  Unable to connect to azure.archive.ubuntu.com:http:
Err:26 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-cloud-tools-common all 5.4.0-147.164
  Unable to connect to azure.archive.ubuntu.com:http:
Err:27 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-tools-common all 5.4.0-147.164
  Unable to connect to azure.archive.ubuntu.com:http:
Fetched 9248 kB in 30s (304 kB/s)

[stderr]
buntu3.21_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http:
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/s/systemd/libudev1_245.4-4ubuntu3.21_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http:
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/s/systemd/systemd-sysv_245.4-4ubuntu3.21_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http:
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/s/systemd/libpam-systemd_245.4-4ubuntu3.21_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http:
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/a/apparmor/libapparmor1_2.13.3-7ubuntu5.2_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http:
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/s/systemd/systemd_245.4-4ubuntu3.21_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http:
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/s/systemd/libsystemd0_245.4-4ubuntu3.21_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http:
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/s/samba/libwbclient0_4.15.13+dfsg-0ubuntu0.20.04.2_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http:
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/d/distro-info-data/distro-info-data_0.43ubuntu1.12_all.deb  Unable to connect to azure.archive.ubuntu.com:http:
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/s/sudo/sudo_1.8.31-1ubuntu1.5_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http:
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/t/tzdata/tzdata_2023c-0ubuntu0.20.04.0_all.deb  Unable to connect to azure.archive.ubuntu.com:http:
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/u/ubuntu-advantage-tools/ubuntu-advantage-tools_27.14.4~20.04_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http:
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/v/vim/vim_8.1.2269-1ubuntu5.13_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http:
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/v/vim/vim-tiny_8.1.2269-1ubuntu5.13_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http:
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/v/vim/vim-runtime_8.1.2269-1ubuntu5.13_all.deb  Unable to connect to azure.archive.ubuntu.com:http:
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/v/vim/xxd_8.1.2269-1ubuntu5.13_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http:
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/v/vim/vim-common_8.1.2269-1ubuntu5.13_all.deb  Unable to connect to azure.archive.ubuntu.com:http:
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/a/apparmor/apparmor_2.13.3-7ubuntu5.2_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http:
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/a/apport/python3-problem-report_2.20.11-0ubuntu27.26_all.deb  Unable to connect to azure.archive.ubuntu.com:http:
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/a/apport/python3-apport_2.20.11-0ubuntu27.26_all.deb  Unable to connect to azure.archive.ubuntu.com:http:
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/a/apport/apport_2.20.11-0ubuntu27.26_all.deb  Unable to connect to azure.archive.ubuntu.com:http:
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/b/bolt/bolt_0.9.1-2~ubuntu20.04.2_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http:
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/l/linux/linux-cloud-tools-common_5.4.0-147.164_all.deb  Unable to connect to azure.archive.ubuntu.com:http:
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/l/linux/linux-tools-common_5.4.0-147.164_all.deb  Unable to connect to azure.archive.ubuntu.com:http:
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?`

**Comment by LiliDeng** [comment]
> > > This is also impacting us. Any fix for it?
> > 
> > 
> > is still on-going? please copy the error message
> 
> We are getting the following error
> 
> `Unable to connect to azure.archive.ubuntu.com:http: Err:19 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 xxd amd64 2:8.1.2269-1ubuntu5.13 Unable to connect to azure.archive.ubuntu.com:http: Err:20 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 vim-common all 2:8.1.2269-1ubuntu5.13 Unable to connect to azure.archive.ubuntu.com:http: Err:26 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-cloud-tools-common all 5.4.0-147.164 Unable to connect to azure.archive.ubuntu.com:http: Err:27 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-tools-common all 5.4.0-147.164 Unable to connect to azure.archive.ubuntu.com:http: Fetched 9248 kB in 30s (304 kB/s)
> 
> [stderr] buntu3.21_amd64.deb Unable to connect to azure.archive.ubuntu.com:http: E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/s/systemd/libudev1_245.4-4ubuntu3.21_amd64.deb Unable to connect to azure.archive.ubuntu.com:http: E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/s/systemd/systemd-sysv_245.4-4ubuntu3.21_amd64.deb Unable to connect to azure.archive.ubuntu.com:http:
> 
> E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/l/linux/linux-tools-common_5.4.0-147.164_all.deb Unable to connect to azure.archive.ubuntu.com:http: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?`

could you please run `apt update` firstly?

**Comment by qaiserali** [comment]
> > > > This is also impacting us. Any fix for it?
> > > 
> > > 
> > > is still on-going? please copy the error message
> > 
> > 
> > We are getting the following error
> > `Unable to connect to azure.archive.ubuntu.com:http: Err:19 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 xxd amd64 2:8.1.2269-1ubuntu5.13 Unable to connect to azure.archive.ubuntu.com:http: Err:20 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 vim-common all 2:8.1.2269-1ubuntu5.13 Unable to connect to azure.archive.ubuntu.com:http: Err:26 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-cloud-tools-common all 5.4.0-147.164 Unable to connect to azure.archive.ubuntu.com:http: Err:27 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-tools-common all 5.4.0-147.164 Unable to connect to azure.archive.ubuntu.com:http: Fetched 9248 kB in 30s (304 kB/s)
> > [stderr] buntu3.21_amd64.deb Unable to connect to azure.archive.ubuntu.com:http: E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/s/systemd/libudev1_245.4-4ubuntu3.21_amd64.deb Unable to connect to azure.archive.ubuntu.com:http: E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/s/systemd/systemd-sysv_245.4-4ubuntu3.21_amd64.deb Unable to connect to azure.archive.ubuntu.com:http:
> > E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/l/linux/linux-tools-common_5.4.0-147.164_all.deb Unable to connect to azure.archive.ubuntu.com:http: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?`
> 
> could you please run `apt update` firstly?

I already run `apt update` and it seems that has fixed the issue.

**Comment by in-fke** [comment]
Unstable again!? Using `ubuntu-latest`
```
W: Tried to start delayed item http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 libavcodec58 amd64 7:4.4.2-0ubuntu0.22.04.1, but failed 
W: Tried to start delayed item http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 libavformat58 amd64 7:4.4.2-0ubuntu0.22.04.1, but failed 
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/x/x264/libx264-163_0.163.3060%2bgit5db6aa6-2build1_amd64.deb 503 Service Unavailable [IP: 20.54.144.51 80] 
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/x/xvidcore/libxvidcore4_1.3.7-1_amd64.deb 503 Service Unavailable [IP: 20.54.144.51 80] 
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/z/zvbi/libzvbi-common_0.2.35-19_all.deb 503 Service Unavailable [IP: 20.54.144.51 80] 
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/z/zvbi/libzvbi0_0.2.35-19_amd64.deb 503 Service Unavailable [IP: 20.54.144.51 80] 
```

**Comment by amotl** [comment]
One of our jobs also just tripped over for the same reasons, but it is succeeding now again.

-- https://github.com/crate/crate-docs-theme/actions/runs/4982713337/jobs/8918772197#step:4:244

**Comment by lextoumbourou** [comment]
Down again.

```
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/libv/libva/va-driver-all_2.14.0-1_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http:
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/libv/libvdpau/vdpau-driver-all_1.4-3build2_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http:
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/p/pocketsphinx/pocketsphinx-en-us_0.8.0%2breal5prealpha%2b1-14ubuntu1_all.deb  Unable to connect to azure.archive.ubuntu.com:http:
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

Quite a show-stopper when this happens. We have `apt-get update --fix-missing` running in CI, but it doesn't seem to fix it.

**Comment by LiliDeng** [comment]
> Down again.
> 
> ```
> E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/libv/libva/va-driver-all_2.14.0-1_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http:
> E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/libv/libvdpau/vdpau-driver-all_1.4-3build2_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http:
> E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/p/pocketsphinx/pocketsphinx-en-us_0.8.0%2breal5prealpha%2b1-14ubuntu1_all.deb  Unable to connect to azure.archive.ubuntu.com:http:
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
> ```
> 
> Quite a show-stopper when this happens. We have `apt-get update --fix-missing` running in CI, but it doesn't seem to fix it.

let me create ubuntu case ...

**Comment by lextoumbourou** [comment]
@LiliDeng can you tell me more about that? How do you create a Ubuntu case?

**Comment by LiliDeng** [comment]
> or try with --fix-missing?

firstly, you need a ubuntu account, then you can create case here 
https://portal.support.canonical.com/ua/s/case/5008e00000EFPVNAA5/unable-to-connect-to-azurearchiveubuntucomhttp-ip-4011946219-80

**Comment by LiliDeng** [comment]
> 

have you retried, the issue still there? I only repro once.

**Comment by in-fke** [comment]
Seemed to be OK the last two hours.

**Comment by in-fke** [comment]
Maybe also follow / comment / vote (?) this MS Question:
https://learn.microsoft.com/en-us/answers/questions/1168604/unable-to-connect-to-azure-archive-ubuntu-com

**Comment by AmitArie** [comment]
still happens :(
<img width="1344" alt="Screenshot 2023-05-17 at 10 05 23" src="https://github.com/actions/runner-images/assets/16286605/234d9aef-c249-4eb8-9e74-a8fbb5306be0">

**Comment by GraemeF** [comment]
After many failures my build just succeeded, so hopefully things are starting to settle. There was an [upstream outage](https://status.canonical.com/#/incident/KNms6QK9ewuzz-7xUsPsNylV20jEt5kyKsd8A-3ptQEzJ9gnukpE8k91hwo6MUodpeX5-g03pfY0LWi6-x2ETA==) that was resolved earlier, maybe that was it.

**Comment by josias-r** [comment]
Also experiencing the issue w/ playwright

**Comment by allanlewis** [comment]
This is happening for me again today.

**Comment by onuruzun** [comment]
this happened today too:

![image](https://github.com/actions/runner-images/assets/21043314/83b58cf1-8d0f-4936-8efb-4de290f40408)

**Comment by onuruzun** [comment]
still happens:

<img width="1206" alt="image" src="https://github.com/actions/runner-images/assets/21043314/bc8b5c32-53ba-4254-a952-9020785c85e4">

**Comment by sebthom** [comment]
@onuruzun you can give this github action a try [vegardit/fast-apt-mirror.sh](https://github.com/vegardit/fast-apt-mirror.sh)

**Comment by keamas** [comment]
Hi,
I have the same issue when using the azure loadbalancer to access the internet
