### ISSUE TITLE
Error CS2044: /sourcelink switch is only supported when emitting PDB, error CS2045: /embed switch is only supported when emitting a PDB.,  Java SDK default drop to version 1.8.0

### ISSUE THREAD

**Issue by denisyakimov07** [actions/runner-images#8837]
### Description

After release 20231115.2.0 my Android build started falling. 
The reason: the Java SDK for default became Java SDK version 1.8.0

### **Image version: '20231115.2.0'**
![image](https://github.com/actions/runner-images/assets/59424027/a8984f8c-b9a2-4049-a29b-7f3a6dfc3399)

### **Image version: '20231029.1.0'**
![image](https://github.com/actions/runner-images/assets/59424027/3efb5615-1bf5-4b59-8164-6a08efbb1158)

The first problem I am working around is setting up Java SDK version manually.
![image](https://github.com/actions/runner-images/assets/59424027/e29e992c-721f-46e7-9ae9-f4eb5cd9d411)

After fix, we started to see other problems during the production Android build. 

`CSC : error CS2044: /sourcelink switch is only supported when emitting PDB. [D:\a\1\s\************************.csproj]`
`CSC : error CS2045: /embed switch is only supported when emitting a PDB. [D:\a\1\s\*************************.csproj]`

There are no changes in the source code between builds.
Some default settings are missing in the new image.  

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20231115.2.0

### Is it regression?

20231029.1.0

### Expected behavior

Remove default flag **PDB** for - task: XamarinAndroid@1

### Actual behavior

Flag is enabled **PDB** for - task: XamarinAndroid@1

### Repro steps

- task: XamarinAndroid@1 failing 

![image](https://github.com/actions/runner-images/assets/59424027/83e8189f-c385-44d0-b880-73a1194754a0)

**Comment by denisyakimov07** [comment]
I was able to fix the Error CS2044 and error CS2045. 

After research, we can see the difference in 2 runs. 
### **image version: '20231115.2.0'**
![image](https://github.com/actions/runner-images/assets/59424027/aec49ad5-3212-4ecd-bd57-14276c22ccf1)

### **image version: '20231029.1.0'**
![image](https://github.com/actions/runner-images/assets/59424027/4d2c050f-d5c3-46aa-ac5f-6f6f6ae811a3)

In my case, one of the dependent projects had no release configuration, debug only. Another project was fixed when i add  

```
    <DebugType>None</DebugType>
    <DebugSymbols>false</DebugSymbols>
```

![image](https://github.com/actions/runner-images/assets/59424027/664741b3-83e0-4c0d-81cb-63b002059448)

**Comment by gtbuchanan** [comment]
I can confirm this broke all of our Xamarin Android builds with the following error:
```
15:14:14 [DBG] C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(254,5): error XA0031: Java SDK 11.0 or above is required when using $(TargetFrameworkVersion) v13.0. [D:\a\1\s\src\**redacted**.csproj::TargetFramework=MonoAndroid13.0]
15:14:14 [DBG] C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(254,5): error XA0031: Download the latest JDK at: https://aka.ms/msopenjdk [D:\a\1\s\src\**redacted**.csproj::TargetFramework=MonoAndroid13.0]
15:14:14 [DBG] C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(254,5): error XA0031: Note: the Android Designer is incompatible with Java SDK 11.0: https://aka.ms/vs2019-and-jdk-11 [D:\a\1\s\src\**redacted**.csproj::TargetFramework=MonoAndroid13.0]
```
We don't use the task. We use raw MSBuild. Here's the internal link:

https://dev.azure.com/energyworldnet/proddev/_build/results?buildId=13228&view=logs&s=7d4e458d-e0e0-5f89-c72d-7371ef61b09b

**Comment by mikhailkoliada** [comment]
Hello! The xamarin components of VS 17.8 started to require JDK 11 it seems, the default JDK version on the windows-2022 image is 8 so that's why you started seeing this error. You should not rely on the JDK version image set as default and did right with `JavaToolInstaller@0` usage (alternatively the `actions/setup-java` should be used if one is using GitHub Actions rather than Azure DevOps). It looks like nothing actable for us left here, so I am going to close the issue, feel free to reach us out again if some other questions left.

**Comment by gtbuchanan** [comment]
I've confirmed that running the `JavaToolInstaller` task before building our Xamarin projects fixed our issues on both Linux and Windows.

**Comment by lhughey** [comment]
This issue seems to be have multiple dependencies in certain projects. I'm working on a project that I've updated the Java SDK via the JavatoolInstaller as evidenced of these lines from the logs

```
_ResolveAndroidTooling:
  Found Java SDK version 11.0.21.
  Found Java SDK version 11.0.21.
```

I still get this error, even after disabling debugging in the project configuration using the following values in the project file

`    <DebugType>None</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <Optimize>true</Optimize>`


Here is the error I'm getting after setting the Java version and setting the debug type.
```
 ##[error]CSC(0,0): Error CS2044: /sourcelink switch is only supported when emitting PDB.
2023-12-01T22:10:20.5351460Z CSC : error CS2044: /sourcelink switch is only supported when emitting PDB. [D:\a\1\s\xxxx.Mobile.Localization\xxxLocalization.csproj]
2023-12-01T22:10:20.5355627Z ##[error]CSC(0,0): Error CS2045: /embed switch is only supported when emitting a PDB.
2023-12-01T22:10:20.5357503Z CSC : error CS2045: /embed switch is only supported when emitting a PDB. [D:\a\1\s\xxx.Localization\xx
```

This is frustrating because the issue was resolved on another configuration in the same project using the combination of the JavatoolInstaller and explicitly disabling debugging in the project file.
