### ISSUE TITLE
Ubuntu image build error

### ISSUE THREAD

**Issue by jaswant-dnv** [actions/runner-images#9715]
### Description

Ubuntu image build error for gpgkey

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image 20240414.1.0 

### Is it regression?

N/A

### Expected behavior

Image build completes

### Actual behavior

==> azure-arm.build_image: gpg: keyserver receive failed: Connection timed out
==> azure-arm.build_image: Provisioning step had errors: Running the cleanup provisioner, if present...
==> azure-arm.build_image: 
==> azure-arm.build_image: Deleting Virtual Machine deployment and its attatched res

### Repro steps

rerun pipeline

**Comment by Alexey-Ayupov** [comment]
Hello @jaswant-dnv. We aware of the problem with gpg during "Heroku" installation. Do you have the same issue? From the provided log it is not obvious what script cause the issue.

**Comment by jaswant-dnv** [comment]
azure-arm.build_image: Running tests from '/imagegeneration/tests/Tools.Tests.ps1'
    azure-arm.build_image: Describing clang
    azure-arm.build_image:   [+] clang 13 263ms (226ms|37ms)
    azure-arm.build_image:   [+] clang 14 176ms (174ms|2ms)
    azure-arm.build_image:   [+] clang 15 185ms (182ms|3ms)
    azure-arm.build_image: Tests completed in 1.45s
    azure-arm.build_image: Tests Passed: 3, Failed: 0, Skipped: 0 NotRun: 94
==> azure-arm.build_image: Provisioning with shell script: /agent/_work/1/s/runner-images/images/ubuntu/templates/../scripts/build/install-swift.sh
==> azure-arm.build_image: Downloading package from https://swift.org/builds/swift-5.10-release/ubuntu2204/swift-5.10-RELEASE/swift-5.10-RELEASE-ubuntu22.04.tar.gz to /tmp/swift-5.10-RELEASE-ubuntu22.04.tar.gz...
##[debug]Agent environment resources - Disk: / Available 31174.00 MB out of 85160.00 MB, Memory: Used 1330.00 MB out of 15981.00 MB, CPU: Usage 1.42%
==> azure-arm.build_image: Package downloaded in 6 seconds
==> azure-arm.build_image: gpg: directory '/root/.gnupg' created
==> azure-arm.build_image: gpg: keybox '/root/.gnupg/pubring.kbx' created
##[debug]Agent environment resources - Disk: / Available 31174.00 MB out of 85160.00 MB, Memory: Used 1334.00 MB out of 15981.00 MB, CPU: Usage 1.41%
##[debug]Agent environment resources - Disk: / Available 31174.00 MB out of 85160.00 MB, Memory: Used 1331.00 MB out of 15981.00 MB, CPU: Usage 1.41%
##[debug]Agent environment resources - Disk: / Available 31174.00 MB out of 85160.

**Comment by Alexey-Ayupov** [comment]
Hi @jaswant-dnv. We have fixed the problematic script and now it works in our pipelines. Please update your fork and try again.

If you have other questions feel free to reach us.

**Comment by jaswant-dnv** [comment]
We still observe same error

==> azure-arm.build_image: Provisioning with shell script: /agent/_work/1/s/runner-images/images/ubuntu/templates/../scripts/build/install-swift.sh
==> azure-arm.build_image: Downloading package from https://swift.org/builds/swift-5.10-release/ubuntu2204/swift-5.10-RELEASE/swift-5.10-RELEASE-ubuntu22.04.tar.gz to /tmp/swift-5.10-RELEASE-ubuntu22.04.tar.gz...
==> azure-arm.build_image: gpg: directory '/root/.gnupg' created
==> azure-arm.build_image: gpg: keybox '/root/.gnupg/pubring.kbx' created
==> azure-arm.build_image: gpg: keyserver receive failed: Connection timed out
==> azure-arm.build_image: Provisioning step had errors: Running the cleanup provisioner, if present...
==> azure-arm.build_image: 
==> azure-arm.build_image: Deleting Virtual Machine deployment and its attatched resources

**Comment by pelu28** [comment]
error still occuring with same error message as above

**Comment by arashjalalat** [comment]
I can confirm that the issue is still occurring, tried on Ubuntu 20.04 and 22.04

**Comment by jaswant-dnv** [comment]
https://github.com/actions/runner-images/issues/9788 raised

**Comment by LokeshNagireddy** [comment]
Hi All,

in the same step of installing swift, im getting below error.

2024-05-06T09:51:19.7580075Z ==> azure-arm.build_image: Provisioning with shell script: /azp/_work/1/s/runner-images/images/ubuntu/templates/../scripts/build/install-swift.sh
2024-05-06T09:51:20.4577391Z ==> azure-arm.build_image: Downloading package from https://swift.org/builds/swift-5.10-release/ubuntu2204/swift-5.10-RELEASE/swift-5.10-RELEASE-ubuntu22.04.tar.gz to /tmp/swift-5.10-RELEASE-ubuntu22.04.tar.gz...
2024-05-06T09:51:29.3047349Z ==> azure-arm.build_image: Package downloaded in 9 seconds
2024-05-06T09:51:29.3349091Z ==> azure-arm.build_image: gpg: directory '/root/.gnupg' created
2024-05-06T09:51:29.3352605Z ==> azure-arm.build_image: gpg: keybox '/root/.gnupg/pubring.kbx' created
2024-05-06T09:59:00.3610624Z ==> **azure-arm.build_image: gpg: keyserver receive failed: Connection timed out**

Do i need to create a new bug, or this bug is enough to track this error? Please let me know.

Thanks

**Comment by AvatarrX** [comment]
facing the same issue, any updated?

==> azure-arm.build_custom_image: Provisioning with shell script: runner-images/images/ubuntu/templates/../scripts/build/install-swift.sh
==> azure-arm.build_custom_image: Downloading package from https://swift.org/builds/swift-5.10.1-release/ubuntu2204/swift-5.10.1-RELEASE/swift-5.10.1-RELEASE-ubuntu22.04.tar.gz to /tmp/swift-5.10.1-RELEASE-ubuntu22.04.tar.gz...
==> azure-arm.build_custom_image: Package downloaded in 5 seconds
==> azure-arm.build_custom_image: gpg: directory '/root/.gnupg' created
==> azure-arm.build_custom_image: gpg: keybox '/root/.gnupg/pubring.kbx' created
==> azure-arm.build_custom_image: gpg: keyserver receive failed: Connection timed out

Thank you
